### ISSUE TITLE
glitr install

### ISSUE THREAD

**Issue by antoine4ucsd** [USAID-OHA-SI/glitr#85]
Hello
sorry for bothering with a basic question but I am unable to install glitr after installing pak (Macbook Pro )

here's the message
```
pak::pak("USAID-OHA-SI/glitr")
                                                                           
→ Will install 1 package.
→ Will download 1 package with unknown size.
+ glitr   0.2.4 👷🏿🔧 ⬇ (GitHub: e03f617)
ℹ Getting 1 pkg with unknown size
✔ Cached copy of glitr 0.2.4 (source) is the latest build
✔ No downloads needed, all packages are cached
ℹ Building glitr 0.2.4
Error:        
! error in pak subprocess
Caused by error: 
! Could not find tools necessary to compile a package
```

I have devtools and pak installed.

thank you!

**Comment by achafetz** [comment]
We typically work on PCs, but tested this out this morning on a Mac and were able to install using `pak` without an issue. The error `pak` returns in your `reprex` above unfortunately isn't very useful - "! Could not find tools necessary to compile a package".

My only recommendation would be trying to install through `remotes` instead of `pak` - `remotes::install_github("USAID-OHA-SI/glitr")`

**Comment by antoine4ucsd** [comment]
I confirm it works fine with remotes. thank you!
